In [ ]:
import cv2
import numpy as np 
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
def Capture_frames(videopath,path_to_store):
    os.chdir(path_to_store)
    video_obj = cv2.VideoCapture(videopath) 
    c,s = 0,1
    wait = 0
    if video_obj.isOpened() == False:
        print("Error in opening video file")
    while s:
        s,img = video_obj.read() 
        if img is None:
            break
        print(img.shape)
        #cv2.imwrite("frame%d.png" % c, img) 
        key = cv2.waitKey(100)
        wait = wait+100
        print("length of image :",len(img))
        #rotated_image1 = img.rotate(180)
        img = cv2.resize(img, (540, 380), fx = 0, fy = 0,
                         interpolation = cv2.INTER_CUBIC)
        #image = cv2.rotate(img, cv2.ROTATE_180)
        print("width height fps frame_count ",video_obj.get(3),video_obj.get(4),video_obj.get(5),video_obj.get(6))
        if wait == 500:
            print("wait",img,c)
            filename = 'Frame_'+str(c)+'.jpg'
            cv2.imwrite(filename, img)
            c += 1
            wait = 0
            print("added Frame ",c)
        #cv2.imshow('Frame', image)

In [ ]:
Capture_frames("/content/drive/MyDrive/ MAJOR PROJECT B TECH 4th YEAR/vehicle-video1-slowed.mp4","/content/drive/MyDrive/ MAJOR PROJECT B TECH 4th YEAR/Frames_Folder")

Streaming output truncated to the last 5000 lines.
width height fps frame_count  352.0 640.0 30.0 828601953.0
(640, 352, 3)
length of image : 640
width height fps frame_count  352.0 640.0 30.0 828601953.0
wait [[[241 191 149]
  [223 173 131]
  [213 163 122]
  ...
  [ 21  37  24]
  [ 26  42  29]
  [ 29  45  32]]

 [[220 170 128]
  [222 172 130]
  [230 180 138]
  ...
  [ 20  36  23]
  [ 20  36  23]
  [ 21  37  24]]

 [[219 169 127]
  [235 185 143]
  [251 201 159]
  ...
  [ 15  31  18]
  [ 15  31  18]
  [ 16  32  19]]

 ...

 [[ 77  79  74]
  [ 78  79  74]
  [ 78  80  75]
  ...
  [149 163 168]
  [151 165 170]
  [152 166 171]]

 [[ 73  77  72]
  [ 73  77  72]
  [ 73  77  72]
  ...
  [154 168 173]
  [159 173 178]
  [161 175 180]]

 [[ 71  75  70]
  [ 72  76  71]
  [ 72  76  71]
  ...
  [152 166 171]
  [155 169 174]
  [157 171 176]]] 100
added Frame  101
(640, 352, 3)
length of image : 640
width height fps frame_count  352.0 640.0 30.0 828601953.0
(640, 352, 3)
length of image : 640
width he